- name: Escape HTML for email
  run: |
    echo "<!DOCTYPE html>
    <html>
    <head>
      <title>New Issue Assignment</title>
      <style>
        /* ... your CSS ... */
      </style>
    </head>
    <body>
      <div class='container'>
        <h1>You've been assigned to an issue!</h1>
        <p>Hi ${{ github.event.assignee.login }},</p>
        <p>You have been assigned to the following issue:</p>
        <p><strong>Title:</strong> ${{ github.event.issue.title }}</p>
        <p><strong>URL:</strong> <a href='{{ github.event.issue.html_url }}'>{{ github.event.issue.html_url }}</a></p>
      </div>
    </body>
    </html>" | sed 's/&/\&/g; s/</\</g; s/>/\>/g' > email_content.txt
- name: Send mail to assignee
  uses: JaSiLez/smtp-notifier@v1.1.2
  with:
    server_address: smtp.gmail.com
    server_port: 465
    username: ${{ secrets.MAIL_USERNAME }}
    password: ${{ secrets.MAIL_PASSWORD }}
    subject: "New Issue Assignment: ${{ github.event.issue.title }}"
    to: ${{ github.event.assignee.email || format('{0}@gmail.com', github.event.assignee.login) }}
    from: Issue Notifier <no-reply@example.com>
    body: $(cat email_content.txt)
    secure: true
